os:
    - linux 
    - osx
language: c

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4

env:
    - NUMPY_VERSION=1.8 PYTHON_VERSION=2.6
    - NUMPY_VERSION=1.8 PYTHON_VERSION=2.7
    - NUMPY_VERSION=1.8 PYTHON_VERSION=3.3
    - NUMPY_VERSION=1.8 PYTHON_VERSION=3.4
    - NUMPY_VERSION=1.9 PYTHON_VERSION=2.6
    - NUMPY_VERSION=1.9 PYTHON_VERSION=2.7
    - NUMPY_VERSION=1.9 PYTHON_VERSION=3.3
    - NUMPY_VERSION=1.9 PYTHON_VERSION=3.4

before_install:
    - if  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose cython
    - if [ $PYTHON_VERSION == 2.6 ]; then conda install --yes argparse; fi
    - python setup.py install

script:
    - python setup.py build
    - python setup.py build_ext

#notifications:
#  email: false
