name: tests-i386

on:
  push:
    branches:
      - master
  pull_request: null


jobs:
  tests:
    name: tests
    strategy:
      fail-fast: false

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          architecture: x86
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: install deps
        shell: bash -l {0}
        run: pip install numpy

      - name: test build and pytest
        shell: bash -l {0}
        run: |
          pip install -e . 
          SKIP_BZIP_TEST=true pytest -vv fitsio
