name: tests-i386

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  tests-i386:
    name: tests-i386
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: install deps
        shell: bash -l {0}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get -y install --allow-downgrades gcc-multilib g++-multilib libgcc-s1:i386 libstdc++6:i386 libpcre3-dev:i386 libglib2.0-dev:i386 python3:i386 python3-apt:i386 libpython3-stdlib:i386

      - name: install python deps
        shell: bash -l {0}
        run: |
          pip install numpy pytest

      - name: test build
        shell: bash -l {0}
        run: |
          pip install -e . 
          SKIP_BZIP_TEST=true pytest -vv fitsio
