name: Wheels
on:
  release:
    types:
      - published
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-20.04
          - macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: joerick/cibuildwheel@v1.10.0
        env:
          CIBW_BUILD: "cp3?-*"
          CIBW_BEFORE_BUILD_LINUX: yum install -y bzip2-devel
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.9"
      - name: Build sdist
        run: |
          python -m pip install -U pip build
          python -m build --sdist .
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

#   # Uncomment this section to automatically upload release to PyPI
#   upload_pypi:
#     needs: [build_wheels, build_sdist]
#     runs-on: ubuntu-latest
#     if: github.event_name == 'release' && github.event.action == 'published'
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: artifact
#           path: dist

#       - uses: pypa/gh-action-pypi-publish@v1.4.2
#         with:
#           user: __token__
#           password: ${{ secrets.pypi_password }}
